### ISSUE TITLE
Using Typescript 4.3 throws unhandled exception

### ISSUE THREAD

**Issue by lolleko** [TypeScriptToLua/TypeScriptToLua#1025]
Repro: https://github.com/Zamiell/tstl-bug/blob/main/README.md courtesy of @Zamiell

```
/Users/lmbp/Desktop/tstl-bug/node_modules/typescript/lib/typescript.js:110412
                throw e;
                ^

TypeError: tag.text.split is not a function
    at collectAnnotations (/Users/lmbp/Desktop/tstl-bug/node_modules/typescript-to-lua/dist/transformation/utils/annotations.js:31:75)
    at getSignatureAnnotations (/Users/lmbp/Desktop/tstl-bug/node_modules/typescript-to-lua/dist/transformation/utils/annotations.js:84:5)
    at Object.isTupleReturnCall (/Users/lmbp/Desktop/tstl-bug/node_modules/typescript-to-lua/dist/transformation/utils/annotations.js:102:13)
    at Object.exports.transformCallExpression [as transform] (/Users/lmbp/Desktop/tstl-bug/node_modules/typescript-to-lua/dist/transformation/visitors/call.js:169:41)
    at TransformationContext.transformNode (/Users/lmbp/Desktop/tstl-bug/node_modules/typescript-to-lua/dist/transformation/context/context.js:45:62)
    at TransformationContext.transformExpression (/Users/lmbp/Desktop/tstl-bug/node_modules/typescript-to-lua/dist/transformation/context/context.js:57:31)
    at Object.exports.transformExpressionStatement [as transform] (/Users/lmbp/Desktop/tstl-bug/node_modules/typescript-to-lua/dist/transformation/visitors/expression-statement.js:27:28)
    at TransformationContext.transformNode (/Users/lmbp/Desktop/tstl-bug/node_modules/typescript-to-lua/dist/transformation/context/context.js:45:62)
    at /Users/lmbp/Desktop/tstl-bug/node_modules/typescript-to-lua/dist/transformation/context/context.js:71:58
    at Array.flatMap (<anonymous>)
```

**Comment by serofody** [comment]
@lolleko Was the problem solved somehow?

**Comment by lolleko** [comment]
No stick to ts 4.2.3 for now

**Comment by Kalabasa** [comment]
I got this exception by upgrading tstl from 0.39.2 to 0.39.3.

**Comment by Kalabasa** [comment]
Looks like the cause was that `tag.text` is no longer a string, but an array. https://github.com/microsoft/TypeScript/commit/dcc27ebaf2e21a02d89cd3bec4084184996b72f1#diff-9717eb6d935579eea3b5662088dd258d4e1e17e2a405c3f1fa431e981e01b08fL1042-L1045

**Comment by Zamiell** [comment]
Cheers, thanks so much Perry!
