### ISSUE TITLE
Crash from tricky generics

### ISSUE THREAD

**Issue by tomblind** [TypeScriptToLua/TypeScriptToLua#908]
I was playing with generics and managed to crash TSTL. Here's my attempt at boiling it down to an isolated repro:
```ts
type Foo<A extends unknown[]> = (fn: (...args: A) => void) => void;

export function bar<A extends Foo<[]>[]>(...args: A) {
    type X = A extends Foo<infer T>[] ? Foo<T[]> : never;
    return (fn => {}) as X;
}
```

And here's the error:
```
TypeError: Cannot read property 'kind' of undefined
    at Object.parenthesizeArrayTypeMember (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:74192:24)
    at Object.createArrayTypeNode (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:70459:31)
    at typeReferenceToTypeNode (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:38969:44)
    at typeToTypeNodeHelper (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:38766:95)
    at serializeTypeForDeclaration (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:39870:30)
    at symbolToParameterDeclaration (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:39357:41)
    at node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:39305:101
    at Array.map (<anonymous>)
    at signatureToSignatureDeclarationHelper (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:39305:67)
    at createTypeNodeFromObjectType (node_modules/typescript-to-lua/node_modules/typescript/lib/typescript.js:38944:49)
```

Normal TS doesn't seem to have a problem with it, so it's TSTL-specific.

**Comment by tomblind** [comment]
Additional info:
Tracing into TS leads to a return statement generating the offending undefined value with a comment that points to this issue: https://github.com/microsoft/TypeScript/issues/18217
The offending line is here: https://github.com/quantapix/qnarre2/blob/06b41b6754f692f208efccf91bd62fd2feb265c4/semantiq/server/src/compiler/checker/context.ts#L1315

**Comment by tomblind** [comment]
Minimalist repro:
```ts
type Foo = (fn: (...args: [][]) => void) => void;
const foo: Foo = (bar => {});
```

It appears to be triggered by the vararg type of empty tuples (`...args: [][]`). The error occurs calling `typeToTypeNode` on the the type of the initializer `(bar => {})`.

Error:
```
Exception has occurred: TypeError: Cannot read property 'kind' of undefined
  at Object.parenthesizeElementTypeOfArrayType (node_modules\typescript\lib\typescript.js:20825:28)
    at Object.createArrayTypeNode (node_modules\typescript\lib\typescript.js:22343:53)
    at typeReferenceToTypeNode (node_modules\typescript\lib\typescript.js:49344:52)
    at typeToTypeNodeHelper (node_modules\typescript\lib\typescript.js:49085:95)
    at serializeTypeForDeclaration (node_modules\typescript\lib\typescript.js:50323:30)
    at symbolToParameterDeclaration (node_modules\typescript\lib\typescript.js:49803:41)
    at node_modules\typescript\lib\typescript.js:49725:263
    at Array.map (<anonymous>)
    at signatureToSignatureDeclarationHelper (node_modules\typescript\lib\typescript.js:49725:229)
    at createTypeNodeFromObjectType (node_modules\typescript\lib\typescript.js:49296:49)
```

**Comment by tomblind** [comment]
[TS Issue](https://github.com/microsoft/TypeScript/issues/45515)

**Comment by Perryvw** [comment]
No longer reproduces
