### ISSUE TITLE
How to locate the real cause?

### ISSUE THREAD

**Issue by weinixuehao** [TypeScriptToLua/TypeScriptToLua#984]
```
Exception has occurred: ExecutionError: attempt to call a nil value (global '__TS__Class')
  at executeLua (/Users/user/Ctsmed/TypeScriptToLua/test/util.ts:97:16)
    at executeLuaModule (/Users/user/Ctsmed/TypeScriptToLua/test/util.ts:108:12)
    at FunctionTestBuilder.getLuaExecutionResult (/Users/user/Ctsmed/TypeScriptToLua/test/util.ts:295:16)
    at FunctionTestBuilder.descriptor.value (/Users/user/Ctsmed/TypeScriptToLua/test/util.ts:155:49)
    at FunctionTestBuilder.expectNoExecutionError (/Users/user/Ctsmed/TypeScriptToLua/test/util.ts:357:32)
    at FunctionTestBuilder.expectToMatchJsResult (/Users/user/Ctsmed/TypeScriptToLua/test/util.ts:367:32)
    at Object.<anonymous> (/Users/user/Ctsmed/TypeScriptToLua/test/unit/functions/asyncFunctions.spec.ts:8:7)
    at Promise.then.completed (/Users/user/Ctsmed/TypeScriptToLua/node_modules/jest-circus/build/utils.js:198:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/user/Ctsmed/TypeScriptToLua/node_modules/jest-circus/build/utils.js:162:10)
```

**Comment by Perryvw** [comment]
The problem as the error describes is that `__TS__Class` cannot be found, I cannot tell you why without seeing the code causing this. It could be for some reason lualib is not correctly required, or there is a lualib dependency missing, or it could be something else entirely.

One thing you could try is adding the `.debug()` function to your test to log some more information about the test. For example
```ts
util.testFunction`return 4 + 7;`.debug().expectToEqual(11)
```

**Comment by Perryvw** [comment]
Closing because there seems to be no followup, I'm assuming the question is answered.
